### ISSUE TITLE
Astro/Storyblok CMS guide build error when following instructions

### ISSUE THREAD

**Issue by danspratling** [withastro/docs#2227]
## What's the problem?
In the Astro/Storyblok docs, there is a typo in the setup instructions that causes an error across every page where `components` are used. As the code happens to be focused on a component that auto-generates components, it's not clear what's actually causing the problem.

Here's the error that's shown to the user

```
Cannot destructure property 'id' of '(intermediate value)' as it is null.
 error   Cannot destructure property 'id' of '(intermediate value)' as it is null.
  File:
    /Users/dan/Code/storyblok-astro-starter/node_modules/@storyblok/astro/dist/storyblok-astro.mjs:55:23
  Code:
    54 |         for await (const [n, a] of Object.entries(t)) {
    > 55 |           const { id: l } = await this.resolve("/src/" + a + ".astro");
         |                       ^
      56 |           s.push(`import ${g(n)} from "${l}"`);
      57 |         }
      58 |         return `${s.join(";")};export default {${Object.keys(t).map((n) => g(n)).join(",")}}`;
  Stacktrace:
TypeError: Cannot destructure property 'id' of '(intermediate value)' as it is null.
    at Context.load (file:///Users/dan/Code/storyblok-astro-starter/node_modules/@storyblok/astro/dist/storyblok-astro.mjs:55:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.load (file:///Users/dan/Code/storyblok-astro-starter/node_modules/astro/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40507:32)
    at async loadAndTransform (file:///Users/dan/Code/storyblok-astro-starter/node_modules/astro/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:36859:24)

/Users/dan/Code/storyblok-astro-starter/node_modules/shiki/dist/index.js:2213
      throw Error(`No language registration for ${lang}`);
            ^

Error: No language registration for mjs
    at getGrammar (/Users/dan/Code/storyblok-astro-starter/node_modules/shiki/dist/index.js:2213:13)
    at codeToThemedTokens (/Users/dan/Code/storyblok-astro-starter/node_modules/shiki/dist/index.js:2222:26)
    at Object.codeToHtml (/Users/dan/Code/storyblok-astro-starter/node_modules/shiki/dist/index.js:2236:20)
    at getViteErrorPayload (file:///Users/dan/Code/storyblok-astro-starter/node_modules/astro/dist/core/errors/dev/vite.js:90:54)
    at async Timeout._onTimeout (file:///Users/dan/Code/storyblok-astro-starter/node_modules/astro/dist/vite-plugin-astro-server/response.js:18:61)
error Command failed with exit code 1.
```

## Where can it be found or how can it be replicated?
https://docs.astro.build/en/guides/cms/storyblok/#connecting-bloks-to-components
Inside the codeblock -> `components: { blogPostList: ... }`. If you compare this to the codeblock directly above you'll notice that the file locations are different, which is what causes the error.

## How can this problem be resolved?
There are 2 potential fixes

1. is to remove the line of code which simply fixes the error
2. is a more complete solution as other parts of the guide talk about blogPostList as a component that can be _used_ within a page, so updating the docs to account for a blog page which uses a blogPostList component would make the most sense.

**Comment by danspratling** [comment]
I'm happy to take this issue, as it'd be great to dig into the docs code and see how it's running. It's all on a single page (so easier for a first-time contributor like myself) and I'm already playing with Storyblok/Astro so I have the context on the CMS side.

---

Side note: The error I posted above is really not very helpful - if people in the astro discord hadn't pointed me in the right direction I wouldn't have known where to look. Is there any way we can update this error message to be clearer about what's _actually_ wrong?

**Comment by kevinzunigacuellar** [comment]
Hello @danspratlin. Thank you for digging this problem out. I am very sorry that you had to do all this debugging. Looking at the code block I think the path for `blogPostList` should be `src/storyblok/blogPostList.astro` instead of `src/pages/...`
