### ISSUE TITLE
Add Prettier plugin to Editor Setup page

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#425]
Update Editor Setup page to include https://github.com/withastro/prettier-plugin-astro

... and document npnp requirments as per: https://github.com/withastro/prettier-plugin-astro/issues/97#issuecomment-1013645333

**Comment by tinymachine** [comment]
[This Discord message](https://discord.com/channels/830184174198718474/966725001812250694/966807472394367047) from April 21 states there's currently no support for ESLint; perhaps a note that ESLint support is forthcoming could be explicitly stated on the Editor Setup Page as well? I spent some time googling around for this info before remembering to check Discord.

**Comment by djmtype** [comment]
## Software

VS Code - Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:42:05.236Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.4.0

❯ node -v
v16.14.2

❯ npm -v
8.5.0

Astro Prettier extension (https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)

## Steps

1. Installed https://github.com/withastro/prettier-plugin-astro
2. Added `plugins: [require.resolve("prettier-plugin-astro")];` to **.prettierrc.js**
3. Created and added the following to **.prettierrc.json**: 
```json
{
  "overrides": [
    {
      "files": "**/*.astro",
      "options": {
        "parser": "astro"
      }
    }
  ]
}
```
4. Added the following to VS Code **settings.json**: 
```json
"prettier.documentSelectors": ["**/*.astro"],
"[astro]": {
"editor.defaultFormatter": "esbenp.prettier-vscode"
}
```
## Usage 

### PNPM
Using **pnpm** and following these instructions, my code would _only_ format if I ran it as a separate task, `pnpm run format`. 
```
"format": "yarn prettier -w . --plugin-search-dir=."`
```
Otherwise, my files would not format on save (according to my settings) nor when choosing to format my files manually. 
Instead, I would receive the following error: 
```
["INFO" - 5:10:41 PM] Formatting file:///Volumes/Evo/Sites/astro-mtype/src/components/Single.astro
["INFO" - 5:10:41 PM] Using config file at '/Volumes/Evo/Sites/astro-mtype/.prettierrc.json'
["INFO" - 5:10:41 PM] Using ignore file (if present) at /Volumes/Evo/Sites/astro-mtype/.prettierignore
["INFO" - 5:10:41 PM] File Info:
{
  "ignored": false,
  "inferredParser": "astro"
}
["INFO" - 5:10:41 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 5:10:41 PM] Prettier Options:
{
  "filepath": "/Volumes/Evo/Sites/astro-mtype/src/components/Single.astro",
  "parser": "astro"
}
["ERROR" - 5:10:41 PM] Error formatting document.
["ERROR" - 5:10:41 PM] Couldn't resolve parser "astro"
Error: Couldn't resolve parser "astro"
    at requireParser (/Volumes/Evo/Sites/astro-mtype/node_modules/.pnpm/prettier@2.6.2/node_modules/prettier/index.js:7343:15)
    at resolveParser (/Volumes/Evo/Sites/astro-mtype/node_modules/.pnpm/prettier@2.6.2/node_modules/prettier/index.js:7331:16)
    at normalize (/Volumes/Evo/Sites/astro-mtype/node_modules/.pnpm/prettier@2.6.2/node_modules/prettier/index.js:7587:22)
    at formatWithCursor2 (/Volumes/Evo/Sites/astro-mtype/node_modules/.pnpm/prettier@2.6.2/node_modules/prettier/index.js:8849:50)
    at /Volumes/Evo/Sites/astro-mtype/node_modules/.pnpm/prettier@2.6.2/node_modules/prettier/index.js:39174:12
    at Object.format (/Volumes/Evo/Sites/astro-mtype/node_modules/.pnpm/prettier@2.6.2/node_modules/prettier/index.js:39188:12)
    at t.default.result (/Users/scottrod/.vscode/extensions/esbenp.prettier-vscode-9.5.0/src/PrettierEditService.ts:462:46)
    at t.PrettierEditProvider.provideEdits (/Users/scottrod/.vscode/extensions/esbenp.prettier-vscode-9.5.0/src/PrettierEditService.ts:317:11)
    at y.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:98503)
["INFO" - 5:10:41 PM] Formatting completed in 0.005ms.
```

### NPM
Using **npm** I had no issues. Worked as advertised.

**Comment by sarah11918** [comment]
Also adding this info that someone wrote online: https://flaviocopes.com/how-to-format-astro-vscode/

**Comment by sarah11918** [comment]
Capturing the idea of moving any actual documentation of the prettier plugin (and the new ESLint plugin) to their specific integrations docs, so that we only need **mention that they exist** and point to those docs.

From @delucis  :  "we could share a link in Editor Setup saying “Looking for more tooling like Prettier, ESLint, and more? Check out the showcase” ( https://github.com/withastro/docs/issues/634 )

**Comment by sarah11918** [comment]
@djmtype I've made a PR #779 to mention and link to both plugins from the editor setup page in the docs. 

Would you be willing to propose your comments/instructions above in a PR to the README at https://github.com/withastro/prettier-plugin-astro directly? I think we're now thinking of this as content for there, instead of on docs itself.

**Comment by djmtype** [comment]
> @djmtype I've made a PR #779 to mention and link to both plugins from the editor setup page in the docs.
> 
> Would you be willing to propose your comments/instructions above in a PR to the README at https://github.com/withastro/prettier-plugin-astro directly? I think we're now thinking of this as content for there, instead of on docs itself.

@sarah11918 I would except I've run into issues with Prettier and Astro again using npm. 

```
["INFO" - 11:55:40 AM] Formatting file:///Volumes/Evo/Sites/astro-project/src/components/Button.astro
["INFO" - 11:55:40 AM] Using config file at '/Volumes/Evo/Sites/astro-project/.prettierrc.json'
["INFO" - 11:55:40 AM] Using ignore file (if present) at /Volumes/Evo/Sites/astro-project/.prettierignore
["INFO" - 11:55:40 AM] File Info:
{
  "ignored": false,
  "inferredParser": "astro"
}
["INFO" - 11:55:40 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 11:55:40 AM] Prettier Options:
{
  "filepath": "/Volumes/Evo/Sites/astro-project/src/components/Button.astro",
  "parser": "astro"
}
["ERROR" - 11:55:40 AM] Error formatting document.
ParseError: (0 , import__2.default) is not a function
    at error (/Volumes/Evo/Sites/astro-project/node_modules/@astrojs/parser/src/utils/error.ts:40:14)
    at Parser.error (/Volumes/Evo/Sites/astro-project/node_modules/@astrojs/parser/src/parse/index.ts:109:3)
    at Parser.acorn_error (/Volumes/Evo/Sites/astro-project/node_modules/@astrojs/parser/src/parse/index.ts:99:8)
    at read_expression (/Volumes/Evo/Sites/astro-project/node_modules/@astrojs/parser/src/parse/read/expression.ts:252:10)
    at mustache (/Volumes/Evo/Sites/astro-project/node_modules/@astrojs/parser/src/parse/state/mustache.ts:399:22)
    at new Parser (/Volumes/Evo/Sites/astro-project/node_modules/@astrojs/parser/src/parse/index.ts:55:12)
    at Object.parseAstro (/Volumes/Evo/Sites/astro-project/node_modules/@astrojs/parser/src/parse/index.ts:227:17)
    at Object.parse (/Volumes/Evo/Sites/astro-project/node_modules/prettier-plugin-astro/src/parse.ts:3:33)
    at Object.parse (/Volumes/Evo/Sites/astro-project/node_modules/prettier/index.js:7334:23)
    at coreFormat (/Volumes/Evo/Sites/astro-project/node_modules/prettier/index.js:8645:18)
    at formatWithCursor2 (/Volumes/Evo/Sites/astro-project/node_modules/prettier/index.js:8837:18)
    at /Volumes/Evo/Sites/astro-project/node_modules/prettier/index.js:37226:12
    at Object.format (/Volumes/Evo/Sites/astro-project/node_modules/prettier/index.js:37240:12)
    at t.default.result (/Users/scottrod/.vscode/extensions/esbenp.prettier-vscode-9.5.0/src/PrettierEditService.ts:462:46)
    at t.PrettierEditProvider.provideEdits (/Users/scottrod/.vscode/extensions/esbenp.prettier-vscode-9.5.0/src/PrettierEditService.ts:317:11)
    at z.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:105121)
["INFO" - 11:55:40 AM] Formatting completed in 0.009ms.
```

**Comment by djmtype** [comment]
@sarah11918 Seems to be related here: https://github.com/withastro/prettier-plugin-astro/issues/184

I tried installing `npm i -D prettier-plugin-astro@next` which installs `"prettier-plugin-astro": "^0.1.0-next.5"`

Still, if I try to format any astro file via Command Palette it fails. 

I must run this process:  

```
"format:astro": "yarn prettier -w src/**/*.astro --plugin-search-dir=."
```

This formatted all astro files except one, maybe because my JSX was so hideous?
