### ISSUE TITLE
Setting the 'mode' option is required, but is not mentioned in docs

### ISSUE THREAD

**Issue by teinett** [withastro/docs#4387]
### 📝 Issue Description

I got the bug using code from Doc's page

### 📋 On which page(s) it occurs

https://docs.astro.build/en/guides/server-side-rendering/#enabling-ssr-in-your-project

### 🤔 Expected Behavior

The text in docs now:

> Converting a static site to hybrid rendering

> To convert an existing static Astro site to allow hybrid rendering, change the output to 'hybrid' and add an adapter:

> ```
> import { defineConfig } from 'astro/config';
> import nodejs from '@astrojs/node';
> 
> export default defineConfig({
>  adapter: nodejs(),
>  output: 'hybrid',
> });
> ```
> 

### 👀 Current Behavior

I used it in my project and got error:

```
11:10:21 PM [vite] Error when evaluating SSR module /Users/teine/Development/astro-parse-api/astro.config.mjs:
|- Error: [@astrojs/node] Setting the 'mode' option is required.
    at Proxy.createIntegration (file:///Users/teine/Development/astro-parse-api/node_modules/@astrojs/node/dist/index.js:12:11)
    at /Users/teine/Development/astro-parse-api/astro.config.mjs:7:20
    at async instantiateModule (file:///Users/teine/Development/astro-parse-api/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)

[astro] Unable to load your Astro config

 error   [@astrojs/node] Setting the 'mode' option is required.
  File:
    /Users/teine/Development/astro-parse-api/node_modules/@astrojs/node/dist/index.js:12:11
  Code:
    11 |   if (!(userOptions == null ? void 0 : userOptions.mode)) {
    > 12 |     throw new Error(`[@astrojs/node] Setting the 'mode' option is required.`);
         |           ^
      13 |   }
      14 |   let _options;
      15 |   return {
  Stacktrace:
Error: [@astrojs/node] Setting the 'mode' option is required.
    at Proxy.createIntegration (file:///Users/teine/Development/astro-parse-api/node_modules/@astrojs/node/dist/index.js:12:11)
    at /Users/teine/Development/astro-parse-api/astro.config.mjs:7:20
    at async instantiateModule (file:///Users/teine/Development/astro-parse-api/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)
```

### 🖥️ Browser

Any

**Comment by delucis** [comment]
Thanks for reporting @teinett! We do show this in the [Node adapter docs](https://docs.astro.build/en/guides/integrations-guide/node/), but you’re right that this example should include this too. Would you be up for making a PR to fix this?
