### ISSUE TITLE
 gitaction error,cant change es2022 version

### ISSUE THREAD

**Issue by HxSay** [withastro/docs#6789]
error   Top-level await is not available in the configured target environment ("es2020")
  File:
    dist/chunks/pages/记一次Java项目线上线程耗尽的问题排查.md.3257850c.mjs:11:35
  Code:
    1635 |   }).join("");
    > 1636 |   let error = new Error(`${text}${summary}`);
           |               ^
      1637 |   error.errors = errors;
      1638 |   error.warnings = warnings;
      1639 |   return error;
  Stacktrace:
Error: Build failed with 8 errors:
dist/chunks/pages/记一次Java项目线上线程耗尽的问题排查.md.3257850c.mjs:11:35: ERROR: Top-level await is not available in the configured target environment ("es2020")
dist/chunks/pages/记一次Java项目线上线程耗尽的问题排查.md.3257850c.mjs:11:57: ERROR: Top-level await is not available in the configured target environment ("es2020")
dist/chunks/pages/记一次Java项目线上线程耗尽的问题排查.md.3257850c.mjs:11:204: ERROR: Top-level await is not available in the configured target environment ("es2020")
dist/chunks/pages/记一次Java项目线上线程耗尽的问题排查.md.3257850c.mjs:11:[226](https://github.com/HxSay/HxSayBlogs/actions/runs/7793999941/job/21254614401#step:7:227): ERROR: Top-level await is not available in the configured target environment ("es2020")
dist/chunks/pages/记一次Java项目线上线程耗尽的问题排查.md.3257850c.mjs:11:373: ERROR: Top-level await is not available in the configured target environment ("es2020")
...
    at failureErrorWithLog (/home/runner/work/HxSayBlogs/HxSayBlogs/node_modules/esbuild/lib/main.js:1636:15)
    at /home/runner/work/HxSayBlogs/HxSayBlogs/node_modules/esbuild/lib/main.js:1048:25
    at /home/runner/work/HxSayBlogs/HxSayBlogs/node_modules/esbuild/lib/main.js:993:52
    at buildResponseToResult (/home/runner/work/HxSayBlogs/HxSayBlogs/node_modules/esbuild/lib/main.js:1046:7)
    at /home/runner/work/HxSayBlogs/HxSayBlogs/node_modules/esbuild/lib/main.js:1075:16
    at responseCallbacks.<computed> (/home/runner/work/HxSayBlogs/HxSayBlogs/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/home/runner/work/HxSayBlogs/HxSayBlogs/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/home/runner/work/HxSayBlogs/HxSayBlogs/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.

**Comment by HxSay** [comment]
//astro.config.mjs
import { defineConfig } from "astro/config";
import tailwind from "@astrojs/tailwind";
import react from "@astrojs/react";
import partytown from "@astrojs/partytown";
import sitemap from "@astrojs/sitemap";
import remarkGfm from "remark-gfm";
import remarkBreaks from "remark-breaks";
import rehypeSlug from "rehype-slug";
import rehypeAutolinkHeadings from "rehype-autolink-headings";

// https://astro.build/config
export default defineConfig({
  site: "https://genexu.github.io",
  integrations: [
    tailwind(),
    react(),
    partytown({
      config: {
        forward: ["dataLayer.push"],
      },
    }),
    sitemap({
      i18n: {
        defaultLocale: "zh-tw",
        locales: {
          "zh-tw": "zh-TW",
          en: "en-US",
        },
      },
    }),
  ],
  markdown: {
    // https://docs.astro.build/en/guides/markdown-content/#markdown-plugins
    // https://docs.astro.build/en/guides/markdown-content/#customizing-a-plugin
    remarkPlugins: [remarkGfm, remarkBreaks],
    rehypePlugins: [
      rehypeSlug,
      [
        rehypeAutolinkHeadings,
        {
          behavior: "append",
          properties: {
            className: ["anchor"],
          },
          content: {
            type: "element",
            tagName: "span",
            // properties: {
            // 	className: ["icon", "icon-link"],
            // },
            children: [
              {
                type: "text",
                value: "#",
              },
            ],
          },
        },
      ],
    ],
    shikiConfig: {
      // Choose from Shiki's built-in themes (or add your own)
      // https://github.com/shikijs/shiki/blob/main/docs/themes.md
      theme: "dracula",
      // Add custom languages
      // Note: Shiki has countless langs built-in, including .astro!
      // https://github.com/shikijs/shiki/blob/main/docs/languages.md
      langs: [],
      // Enable word wrap to prevent horizontal scrolling
      wrap: false,
    },
  },
  vite: {
    ssr: {
      noExternal: ["react-icons"],
    },
  },
});

**Comment by HxSay** [comment]
//gitpages.yml

name: Deploy Astro site to Pages

on:
  push:
    branches: ["main"]

  # Allows run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write    # To deploy to Pages
  id-token: write # To verify the deployment originates from an appropriate source

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "." 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: ${{ env.BUILD_PATH }}/yarn.lock

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Clear Yarn cache
        run: yarn cache clean

      - name: Install dependencies
        working-directory: ${{ env.BUILD_PATH }}
        run: yarn install

      - name: Build with Astro
        working-directory: ${{ env.BUILD_PATH }}
        run: |
          yarn build \
            --site "${{ steps.pages.outputs.origin }}" \
            --base "${{ steps.pages.outputs.base_path }}" \
            --target es2023
          yarn pagefind

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
