### ISSUE TITLE
Image not found when file name contains a space

### ISSUE THREAD

**Issue by mossymaker** [withastro/docs#8562]
When a markdown document includes an image with a space in the filename, Astro reports ["image not found"](https://docs.astro.build/en/reference/errors/image-not-found/). The URL encoded space seems to get decoded.

_src/content/docs/reference/network/System Diagram.md_
```md
---
title: System Diagram
---

![Network Diagram](../../../../assets/Network%20Diagram.svg)

```

If the file is renamed to remove the space and the path is updated, Astro finds the image.

Here's the trace:

```
ImageNotFound: Could not find requested image `../../../../assets/Network%20Diagram.svg`. Does it exist?
    at LoadPluginContext.load (file:///Users/.../node_modules/astro/dist/assets/vite-plugin-assets.js:179:19)
    at async PluginContainer.load (file:///Users/.../node_modules/vite/dist/node/chunks/dep-BcXSligG.js:49511:22)
    at async loadAndTransform (file:///Users/.../node_modules/vite/dist/node/chunks/dep-BcXSligG.js:52306:22)
    at async instantiateModule (file:///Users/.../node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53309:44)
```

**Comment by sarah11918** [comment]
Hi @mossymaker ! Thank you for mentioning this! However, this is the repo for reporting issues with the documentation site, and I believe this is something that should be brought to the attention of the code repo itself as a potential bug.

Could you please instead [file an issue in the astro code repo](https://github.com/withastro/astro/issues/new?assignees=&labels=&projects=&template=---01-bug-report.yml) and fill out their template for reporting issues like this?

Thank you!
